# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [4]:
import numpy as np

print(np.version.version)

1.14.3


2) Создать нулевой вектор размера 10

In [5]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [7]:
np.full((10), 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [11]:
np.array([i for i in range(10, 100) if not i % 2])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [17]:
mass = np.random.randn((5))
print(mass)
print(mass[::-1])

[ 0.12329902  1.60079316  0.95794021  0.51751494 -0.30432952]
[-0.30432952  0.51751494  0.95794021  1.60079316  0.12329902]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [22]:
np.linspace(0,8,9).reshape((3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [23]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])