# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [9]:
import numpy as np

arr = np.full((4, 4), 7)
for x in range(4):
    arr[x][x] = x + 1
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
arr = np.zeros((5,5))
for x in range(5):
    arr[x] = np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [23]:
arr = np.random.random_sample((100)).reshape(10,10)
print(arr)
print()
for row in arr:
    row -= row.mean()
print(arr)

[[0.7519362  0.87305936 0.26830933 0.51729089 0.64409365 0.82046851
  0.03802374 0.56303549 0.05421829 0.83408002]
 [0.89126498 0.57885757 0.49949513 0.81102263 0.13214786 0.21922308
  0.32944152 0.67967368 0.22155456 0.29939023]
 [0.01963513 0.38152223 0.25858955 0.1232843  0.09969694 0.37911311
  0.18022296 0.03353804 0.97246316 0.36373349]
 [0.22646381 0.16705894 0.64094559 0.96813323 0.95785367 0.84536041
  0.49040462 0.94288168 0.36976711 0.33740879]
 [0.29422813 0.03470488 0.61986425 0.34680451 0.95851066 0.25843257
  0.77268492 0.66680007 0.34731504 0.00111888]
 [0.4336651  0.93465555 0.36259322 0.12430294 0.17356077 0.13883023
  0.09138048 0.27840638 0.59206704 0.22884653]
 [0.73198373 0.08783905 0.11456849 0.79469166 0.25528561 0.78987956
  0.94032375 0.09640346 0.68342167 0.64821043]
 [0.69620308 0.57675387 0.56099767 0.14247718 0.83187186 0.7811651
  0.87355869 0.58749562 0.29459783 0.14897061]
 [0.6754708  0.83526687 0.78075136 0.09918863 0.9572842  0.68899389
  0.00621145 

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [28]:
arr = np.random.random_sample((100)).reshape(10,10)
temp = np.median(arr, axis = 0)
for x in range(arr.shape[1]):
    arr[0:, x:x+1] -= temp[x]
arr

array([[-0.33246071, -0.33332345, -0.05746946,  0.07785769,  0.14961602,
        -0.07139551,  0.02532925, -0.2227595 ,  0.09484407,  0.13389486],
       [-0.00215493,  0.14377792, -0.13302157, -0.07785769, -0.11927398,
         0.33036429, -0.16295969,  0.10977406, -0.0278596 , -0.0426132 ],
       [-0.38757686,  0.0370589 , -0.32898603,  0.31409728,  0.55415091,
         0.16882288,  0.04373206,  0.31745292, -0.1178229 ,  0.19283243],
       [ 0.00215493, -0.10820522, -0.29687025, -0.13062881,  0.56581082,
        -0.26043877, -0.64084155, -0.58012693,  0.34519859, -0.15272573],
       [ 0.28195139, -0.0370589 ,  0.48023707,  0.44694695,  0.58595499,
         0.39882818,  0.25175584, -0.05318757,  0.0278596 , -0.11231832],
       [ 0.1052212 ,  0.17355872,  0.05746946,  0.48642867,  0.10152254,
         0.07139551,  0.19360915,  0.01510125,  0.07574211,  0.31806437],
       [ 0.07763366, -0.23493835,  0.2930761 ,  0.59515502, -0.21153672,
        -0.12821167, -0.39398226,  0.07517566

5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [34]:
arr = np.random.random_sample((25)).reshape(5,5)
min_col = np.min(arr, axis = 0).reshape(5,1)
max_col = np.max(arr, axis = 0).reshape(5,1)
arr = np.concatenate((arr, min_col, max_col), axis=1)
print(arr)

[[0.66794466 0.44090355 0.55173182 0.05193479 0.92931441 0.05932818
  0.74733577]
 [0.05932818 0.75179695 0.56377798 0.06297106 0.24638605 0.44090355
  0.94364518]
 [0.74733577 0.91412948 0.32117242 0.28307848 0.8167581  0.32117242
  0.91745361]
 [0.2479542  0.94364518 0.91745361 0.71439269 0.03690399 0.05193479
  0.94707509]
 [0.7336493  0.77798325 0.35971577 0.94707509 0.27654687 0.03690399
  0.92931441]]


6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [42]:
arr = np.arange(1, 51)
arr1 = arr[arr % 2 != 0].reshape(5,5)
arr2 = arr[arr % 2 == 0].reshape(5,5)
prv = arr1*arr2
print(prv)
np.linalg.inv(prv)

[[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]


array([[ 7.32316981e+11,  5.17623113e+12, -1.99225953e+13,
         2.13872292e+13, -7.37318208e+12],
       [-1.63478256e+13,  3.40052852e+13, -3.92890237e+12,
        -2.87667488e+13,  1.50381914e+13],
       [ 4.46495748e+13, -1.33073243e+14,  1.31322279e+14,
        -4.20231292e+13, -8.75481859e+11],
       [-4.31849408e+13,  1.43425705e+14, -1.71167469e+14,
         8.47975877e+13, -1.38708823e+13],
       [ 1.41508746e+13, -4.95339786e+13,  6.36966882e+13,
        -3.53949390e+13,  7.08135479e+12]])

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [45]:
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])